// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekvxogcxepbnjwjcphjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrdnhvZ2N4ZXBibmp3amNwaGpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzE0NjEsImV4cCI6MjA2MDk0NzQ2MX0.KM-003E4b9Y9WacZ2S0EyhnXLXNRd7qTGo9zwmiCm58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);